---
deployment:
  tasks:
    - export DEPLOYPATH=/home/bukramaby/public_html/
    - /usr/bin/rsync -rlptgoDv --delete --exclude='.git/' --exclude='.gitignore' --exclude='README.md' --exclude='.cpanel.yml' ./ $DEPLOYPATH
    - /bin/echo "Deployment complete"
